### PR TITLE
Added `left` and `right`.

### PR DESCRIPTION
**Pull request by pseudonom**

### CODE REVIEW

**Comment by paf31** [comment]
I'm not sure I see so much value in these honestly. They're easily defined with `either`, and their names clash with `profunctors`.

**Comment by garyb** [comment]
I'm of similar mind, you'd probably end up using `fromMaybe` or `maybe` with them anyway, so may as well just go straight to `either`.

**Comment by pseudonom** [comment]
> not sure I see so much value in these honestly. They're easily defined with `either`

Yeah, they're certainly not essential.

> using `fromMaybe` or `maybe`

I end up using them for monadic chaining with `Maybe` (e.g. combining errors that report their reason for failure and those that don't):

```purescript
foo :: c -> Either a b
bar :: [c] -> Maybe b
bar = right <<< foo <=< head
```

**Comment by garyb** [comment]
Closing this as I think we're not merging it. Thanks though!

**Pull request closed without merging**
