### PR TITLE
correct Semiring instance

### PR DESCRIPTION
**Pull request by matthewleon**
fixes https://github.com/purescript/purescript-either/issues/34

@paf31 recommended just removing the instance, but I think this works instead?

### CODE REVIEW

**Comment by garyb** [comment]
I've created a 0.12 branch and switched this to merge onto that. Will review the change later today, unless someone else gets there first :)

**Comment by garyb** [comment]
I think for now I'll just remove it, and we can talk more about what makes sense as an instance (if anything). This looks about right, but I'm not sure how useful the behaviour is, or if there are perhaps a few options to choose from.

**Comment by hdgarrood** [comment]
This doesn't work either, unfortunately; it won't satisfy the distributivity laws. If you put the below into Try PureScript you'll see that `oopsL` does not equal `oopsR`.

```purescript
module Main where

import Prelude

import Control.Monad.Eff (Eff)
import TryPureScript (DOM, h1, h2, p, text, list, indent, link, render, code)

main :: Eff (dom :: DOM) Unit
main =
    render $ h1 $ text $ show oopsL <> " /= " <> show oopsR

data Either a b = Left a | Right b

instance showEither :: (Show a, Show b) => Show (Either a b) where
  show (Left x) = "(Left " <> show x <> ")"
  show (Right y) = "(Right " <> show y <> ")"
  
oopsL :: Either Int Int
oopsL = Left 1 * (Right 2 + Right 3)

oopsR :: Either Int Int
oopsR = (Left 1 * Right 2) + (Left 1 * Right 3)
    
instance semiringEither :: (Semiring a, Semiring b) => Semiring (Either a b) where
   one = Right one
   mul = semiringHelper mul
   zero = Right zero
   add = semiringHelper add
    
semiringHelper
  :: forall a b
   . Semiring a
  => Semiring b
  => (forall a'. Semiring a' => a' -> a' -> a')
  -> Either a b -> Either a b -> Either a b
semiringHelper op x y =
  case x, y of
      Left x', Left y' -> Left $ x' `op` y'
      Right x', Right y' -> Right $ x' `op` y'
      Left x', _ -> Left x'
      _, Left y' -> Left y'
```

**Comment by matthewleon** [comment]
@hdgarrood good catch.

**Pull request closed without merging**
