### PR TITLE
Show Either's "do notation" similarity to nested if-then-else statement

### PR DESCRIPTION
**Pull request by JordanMartinez**

### CODE REVIEW

**Comment by hdgarrood** [comment]
I think this is probably more suitable for the `Bind (Either e)` instance. I would say that it's really the Bind instance which enables do notation, as for do notation all you really need is `bind`. Personally, I think the Monad instance docs should be left at "The `Monad` instance guarantees that there are both `Applicative` and `Bind` instances for `Either`, and the rest of these docs should be on the Bind instance.

**Comment by hdgarrood** [comment]
I agree that a more intuitive explanation of what the Bind instance does would be good, but I'm not sure pseudocode is the best way of achieving that; I think prose would probably be preferable.

**Comment by hdgarrood** [comment]
The reason that I prefer prose over pseudocode is mostly that not everyone is that familiar with whatever language your pseudocode is based on, and even if they were, they might not be able to work out what e.g. `unwrapRight` or `wrapIntoRight` are supposed to be doing, or might get hung up on the fact that `unwrapRight` doesn't have parens to indicate that it's a function. In general I think prose explanations are less likely to accidentally introduce this kind of inaccessibility where you make assumptions about what the reader knows, or how they are likely to interpret something.

**Comment by JordanMartinez** [comment]
Not using pseudo code makes sense. However, I'm not sure how to write that without it being just as confusing. I feel like a visual of some sorts would explain this much better. Is it possible to include images in documentation?

**Comment by JordanMartinez** [comment]
Also, I explained how the `Array` monad works in `purescript-prelude` via purescript/purescript-prelude#217. It's currently on the `Monad` instance rather than the `Bind` instance. So, I should update it there to be consistent with what we do here.

**Comment by JordanMartinez** [comment]
Rather than using pseudo-code, I explained it using regular PureScript.

I also moved the explanation to the Bind instance.

**Comment by JordanMartinez** [comment]
I had to force-push this because CI was not pulling in the v0.14.0-rc3 binary

**Comment by JordanMartinez** [comment]
CI now builds. Harry, this is the same approach you previously approved regarding `Maybe`'s do notation documentation.

**Review by hdgarrood — APPROVED** [review]
Looks great!

**Pull request merged**
