### PR TITLE
cleaner nested eithers

### PR DESCRIPTION
**Pull request by jdegoes**

### CODE REVIEW

**Comment by jdegoes** [comment]
Same story, no libraries using this.

**Comment by paf31** [comment]
Looks good.

Curious: is this the way the nesting comes out of a nested backticked operator (infixr, I think)?

**Comment by jdegoes** [comment]
No, `a 'foo' c 'foo' d` will come out infixl 9, I think.

That might be a reason for making these left-associative. Actually, I originally wanted to make both nested tuples and nested eithers left-associative, because then you get the most useful definitions for `Functor`, et al. e.g. `Tuple4 a b c d` operates on `d` naturally, because by associativity it's `Tuple (((Tuple a) b) c) d`.

I asked around and discovered that right-associative was the most common way to define these, but still don't have a good reason for it. I'd be happy to change both nested modules to left-associative, if you think that's a good change.

**Comment by paf31** [comment]
I think those are both good reasons to prefer left associative, if infix operators do in fact give things that way round.

**Comment by jdegoes** [comment]
OK, will amend this one and submit another one to change associativity.

**Comment by jdegoes** [comment]
Amended & ready to merge, PR coming up for tuples.

**Comment by paf31** [comment]
:+1: Thanks!

**Pull request merged**
