### PR TITLE
Make fromLeft/fromRight total functions by providing default values

### LINKED ISSUE #47: `fromLeft` / `fromRight` shouldn't be partial
I'd like to have

```purescript
fromLeft :: forall a b. a -> Either a b -> a
fromRight ::  forall a b. b -> Either a b -> b
```
over the current partial

```purescript
fromLeft :: Partial => forall a b. Either a b -> a
fromLeft :: Partial => forall a b. Either a b -> b
```

as typing `either (const a) identity` becomes old rather quickly and I need these functions much more frequently than their partial counterparts. I'm not sure how confusing it would be to define these functions differently in two modules in this package, but even if don't rename the old ones I think this would be a win.

### PR DESCRIPTION
**Pull request by JordanMartinez**
Fixes #47

### CODE REVIEW

**Comment by JordanMartinez** [comment]
Had to force push this because I didn't implement `fromRight` correctly due to putting the `Right b` pattern match after the left's `_` pattern match

**Comment by hdgarrood** [comment]
I don't think it will be totally clear what the "default value" is when these documentation comments are rendered on Pursuit and the definition isn't visible. How about this instead?

> A function that extracts the value from the `Left` data constructor. The first argument is a default value, which will be returned in the case where a `Right` is passed to `fromLeft`.

**Comment by JordanMartinez** [comment]
Yeah, that reads better. I've updated the docs to include that.

**Comment by srghma** [comment]
what if we leave old partial functions, but rename them to `unsafeFromLeft` and `unsafeFromRight`?

**Comment by JordanMartinez** [comment]
> what if we leave old partial functions, but rename them to unsafeFromLeft and unsafeFromRight?

I think keeping them makes sense.

**Comment by garyb** [comment]
I dunno, you can just do `fromLeft crash` with this version 🙂

**Review by hdgarrood — APPROVED** [review]

**Pull request merged**
